CREATE TABLE IF NOT EXISTS urls (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    short_code VARCHAR(10) UNIQUE NOT NULL,
    long_url TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analytics (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    short_code VARCHAR(10) NOT NULL,
    ip VARCHAR(45),
    user_agent TEXT,
    clicked_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
