-- +goose Up
CREATE TABLE IF NOT EXISTS link (
	link_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	original_url TEXT NOT NULL,
	short_code VARCHAR(10) NOT NULL UNIQUE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stat (
	stat_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
	link_id UUID NOT NULL REFERENCES link(link_id) ON DELETE CASCADE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ip VARCHAR(45),
	user_agent TEXT
);

-- +goose Down
DROP TABLE IF EXISTS link;
DROP TABLE IF EXISTS stat;
